version: '3'
services:
  fastapi:
    container_name: fastapi
    build:
      context: .
    image: fastapi-image
    volumes:
      - .:/opt/app
    ports:
      - 8000:8000
    networks:
      - appnet

networks:
  appnet: